DummyBloodGroups = [{
  "id": 1,
  "title": "A+",
  "users_count": 2342,
  "short_description": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
  "description": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
  "url": "https://admin.ch/vel.html?accumsan=condimentum&odio=id&curabitur=luctus&convallis=nec&duis=molestie&consequat=sed&dui=justo&nec=pellentesque&nisi=viverra&volutpat=pede&eleifend=ac&donec=diam&ut=cras&dolor=pellentesque&morbi=volutpat&vel=dui&lectus=maecenas&in=tristique&quam=est&fringilla=et&rhoncus=tempus&mauris=semper&enim=est&leo=quam&rhoncus=pharetra&sed=magna&vestibulum=ac&sit=consequat&amet=metus&cursus=sapien&id=ut&turpis=nunc&integer=vestibulum&aliquet=ante&massa=ipsum&id=primis&lobortis=in&convallis=faucibus&tortor=orci&risus=luctus&dapibus=et&augue=ultrices&vel=posuere&accumsan=cubilia&tellus=curae&nisi=mauris&eu=viverra&orci=diam&mauris=vitae&lacinia=quam&sapien=suspendisse&quis=potenti&libero=nullam&nullam=porttitor&sit=lacus&amet=at&turpis=turpis&elementum=donec&ligula=posuere&vehicula=metus&consequat=vitae&morbi=ipsum&a=aliquam&ipsum=non&integer=mauris&a=morbi&nibh=non&in=lectus&quis=aliquam&justo=sit&maecenas=amet&rhoncus=diam&aliquam=in&lacus=magna&morbi=bibendum&quis=imperdiet&tortor=nullam&id=orci&nulla=pede&ultrices=venenatis&aliquet=non&maecenas=sodales&leo=sed&odio=tincidunt&condimentum=eu&id=felis&luctus=fusce&nec=posuere&molestie=felis"
}, {
  "id": 2,
  "title": "A-",
  "users_count": 9855,
  "short_description": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
  "description": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.",
  "url": "http://merriam-webster.com/turpis/donec/posuere/metus/vitae/ipsum.html?varius=non&integer=mauris&ac=morbi&leo=non&pellentesque=lectus&ultrices=aliquam&mattis=sit&odio=amet&donec=diam&vitae=in&nisi=magna&nam=bibendum&ultrices=imperdiet&libero=nullam&non=orci&mattis=pede&pulvinar=venenatis&nulla=non&pede=sodales&ullamcorper=sed&augue=tincidunt&a=eu&suscipit=felis&nulla=fusce&elit=posuere&ac=felis&nulla=sed&sed=lacus&vel=morbi&enim=sem&sit=mauris&amet=laoreet&nunc=ut&viverra=rhoncus&dapibus=aliquet"
}, {
  "id": 3,
  "title": "B+",
  "users_count": 2546,
  "short_description": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
  "description": "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
  "url": "https://ibm.com/et/ultrices.png?leo=nulla&maecenas=dapibus&pulvinar=dolor&lobortis=vel&est=est&phasellus=donec&sit=odio&amet=justo&erat=sollicitudin&nulla=ut&tempus=suscipit&vivamus=a&in=feugiat&felis=et&eu=eros&sapien=vestibulum&cursus=ac&vestibulum=est&proin=lacinia&eu=nisi&mi=venenatis&nulla=tristique&ac=fusce&enim=congue&in=diam&tempor=id&turpis=ornare&nec=imperdiet&euismod=sapien&scelerisque=urna&quam=pretium&turpis=nisl&adipiscing=ut&lorem=volutpat&vitae=sapien&mattis=arcu&nibh=sed&ligula=augue&nec=aliquam&sem=erat&duis=volutpat&aliquam=in&convallis=congue&nunc=etiam&proin=justo&at=etiam&turpis=pretium&a=iaculis&pede=justo&posuere=in&nonummy=hac&integer=habitasse&non=platea&velit=dictumst&donec=etiam&diam=faucibus&neque=cursus&vestibulum=urna&eget=ut&vulputate=tellus&ut=nulla&ultrices=ut&vel=erat&augue=id&vestibulum=mauris&ante=vulputate&ipsum=elementum&primis=nullam&in=varius&faucibus=nulla&orci=facilisi&luctus=cras&et=non&ultrices=velit&posuere=nec&cubilia=nisi&curae=vulputate&donec=nonummy&pharetra=maecenas&magna=tincidunt&vestibulum=lacus&aliquet=at&ultrices=velit"
}, {
  "id": 4,
  "title": "B-",
  "users_count": 5484,
  "short_description": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
  "description": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.",
  "url": "http://soup.io/vestibulum/rutrum/rutrum/neque/aenean/auctor/gravida.xml?penatibus=interdum&et=mauris&magnis=ullamcorper&dis=purus&parturient=sit&montes=amet&nascetur=nulla&ridiculus=quisque&mus=arcu&vivamus=libero&vestibulum=rutrum&sagittis=ac&sapien=lobortis&cum=vel&sociis=dapibus&natoque=at&penatibus=diam"
}, {
  "id": 5,
  "title": "O+",
  "users_count": 6844,
  "short_description": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
  "description": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
  "url": "http://nsw.gov.au/quam.xml?donec=sapien&odio=quis&justo=libero&sollicitudin=nullam&ut=sit&suscipit=amet&a=turpis&feugiat=elementum&et=ligula&eros=vehicula&vestibulum=consequat"
}, {
  "id": 6,
  "title": "O-",
  "users_count": 2366,
  "short_description": "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
  "description": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
  "url": "https://amazonaws.com/libero/convallis/eget/eleifend.jpg?et=hac&ultrices=habitasse&posuere=platea&cubilia=dictumst&curae=maecenas&nulla=ut&dapibus=massa&dolor=quis&vel=augue"
}, {
  "id": 7,
  "title": "AB+",
  "users_count": 8854,
  "short_description": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
  "description": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
  "url": "https://1und1.de/at/nulla/suspendisse/potenti/cras/in/purus.js?amet=condimentum&sem=neque&fusce=sapien&consequat=placerat&nulla=ante&nisl=nulla&nunc=justo&nisl=aliquam&duis=quis&bibendum=turpis&felis=eget&sed=elit&interdum=sodales&venenatis=scelerisque&turpis=mauris&enim=sit&blandit=amet&mi=eros&in=suspendisse"
}, {
  "id": 8,
  "title": "AB-",
  "users_count": 2245,
  "short_description": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
  "description": "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
  "url": "http://pbs.org/posuere/cubilia/curae/duis.json?ante=non&vel=ligula&ipsum=pellentesque&praesent=ultrices&blandit=phasellus&lacinia=id&erat=sapien&vestibulum=in&sed=sapien&magna=iaculis&at=congue&nunc=vivamus&commodo=metus&placerat=arcu&praesent=adipiscing&blandit=molestie&nam=hendrerit&nulla=at&integer=vulputate&pede=vitae&justo=nisl&lacinia=aenean&eget=lectus&tincidunt=pellentesque&eget=eget&tempus=nunc&vel=donec&pede=quis&morbi=orci&porttitor=eget&lorem=orci&id=vehicula&ligula=condimentum&suspendisse=curabitur&ornare=in"
}]
